# Site settings
title: Shimin Zhang
description: Research
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shimin Zhang
user_description: 
user_title: 
email: shimin.zhang@uni-heidelberg.de
# twitter_username: lorem_ipsum
facebook_username: Shimin Zhang
github_username:  SimoneCheung
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
